# Generated by Django 4.1.7 on 2024-07-04 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(height_field='2', max_length='100', upload_to='club/', width_field='2')),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('R', 'React'), ('A', 'Angular'), ('N', 'Node'), ('P', 'Python'), ('D', 'Database')], max_length=2)),
            ],
        ),
    ]
