# Generated by Django 4.1.7 on 2024-07-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_developer_date_joined_alter_developer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='projects',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(upload_to='media/club/'),
        ),
    ]
